/* autogenerated by Processing revision 1293 on 2025-09-28 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class hackathonGame extends PApplet {

// Arcade Startup Screen in Processing

int screen = 0;  // 0 = menu, 1 = game1, 2 = game2, 3 = game3, 4 = game4

public void setup() {
  /* size commented out by preprocessor */;
  textAlign(CENTER, CENTER);
}

public void draw() {
  background(0);

  if (screen == 0) {
    drawMenu();
  } else if (screen == 1) {
    game1();
  } else if (screen == 2) {
    game2();
  } else if (screen == 3) {
    game3();
  } else if (screen == 4) {
    game4();
  }
}

// ---- MENU ----
public void drawMenu() {
  fill(255);
  textSize(40);
  text("🎮 Arcade Hub 🎮", width/2, 100);

  textSize(24);
  drawButton("Game 1: Skee-Ball", width/2, 200, 200, 50, 1);
  drawButton("Game 2: Whac-a-Mole", width/2, 280, 200, 50, 2);
  drawButton("Game 3: Flappy Retriever", width/2, 360, 200, 50, 3);
  drawButton("Game 4: Pong", width/2, 440, 200, 50, 4);
}

public void drawButton(String label, float x, float y, float w, float h, int gameScreen) {
  if (mouseOver(x, y, w, h)) {
    fill(150, 200, 255);
  } else {
    fill(100, 150, 200);
  }
  rectMode(CENTER);
  rect(x, y, w, h, 10);
  fill(0);
  textSize(18);
  text(label, x, y);

  // Handle click
  if (mousePressed && mouseOver(x, y, w, h)) {
    screen = gameScreen;
  }
}

public boolean mouseOver(float x, float y, float w, float h) {
  return (mouseX > x - w/2 && mouseX < x + w/2 &&
          mouseY > y - h/2 && mouseY < y + h/2);
}

// ---- GAME PLACEHOLDERS ----
public void game1() {
  background(30, 120, 200);
  fill(255);
  text("Skee-Ball Game Placeholder", width/2, height/2);
  backButton();
}

public void game2() {
  background(200, 80, 100);
  fill(255);
  text("Whac-a-Mole Game Placeholder", width/2, height/2);
  backButton();
}

public void game3() {
  flappyDriver();
  backButton();
}

public void game4() {
  background(180, 180, 50);
  fill(0);
  text("Pong Game Placeholder", width/2, height/2);
  backButton();
}

// ---- BACK BUTTON ----
public void backButton() {
  drawButton("⬅ Back to Menu", width/2, height - 50, 200, 40, 0);
}
// Flappy Retriever Game with Score

PImage backdrop;
PImage dog;
PImage movingPart;
PImage topBone;
PImage bottomBone;

float movingX = 0;
float movingSpeed = 3;

float dogPosY = 300;
float velocity = 0;  
float gravity = 1.5f;  
float jump = -13;    
boolean started = false;
boolean initialized = false;
boolean gameOver = false;

float dogX = 180;
float dogW = 100;
float dogH = 100;

int score = 0;  // score counter

ArrayList<Pipe> pipes;

public void flappyDriver() {
  if (!initialized) {
    backdrop = loadImage("background.png");
    dog = loadImage("dog.png");
    movingPart = loadImage("movingPart.png");
    topBone = loadImage("topBone.png");
    bottomBone = loadImage("bottomBone.png");
    if (backdrop == null || dog == null || movingPart == null || topBone == null || bottomBone == null) {
      println("failed to load images");
    }
    pipes = new ArrayList<Pipe>();
    pipes.add(new Pipe(width));  // first pipe starts off-screen
    initialized = true;
  }
  drawFlappy();
}

public void drawFlappy() {
  // background
  image(backdrop, 0, 0);

  // moving ground
  movingX -= movingSpeed;
  if (movingX <= -600) movingX = 0;
  image(movingPart, movingX, 599, 600, 151);
  image(movingPart, movingX + 600, 599, 600, 151);

  // dog movement (only after start)
  if (started && !gameOver) {
    velocity += gravity;
    dogPosY += velocity;
  }

  // floor collision (touching moving ground ends game)
  float groundY = 599;
  float hitOffset = 10; // dog can go 10 pixels lower before losing
  if (dogPosY + dogH >= groundY + hitOffset) {
    dogPosY = groundY - dogH + hitOffset;
    velocity = 0;
    gameOver = true;
  }

  // ceiling limit
  if (dogPosY < 0) {
    dogPosY = 0;
    velocity = 0;
  }

  // draw dog
  image(dog, dogX, dogPosY, dogW, dogH);

  // pipes
  for (int i = pipes.size()-1; i >= 0; i--) {
    Pipe p = pipes.get(i);

    // move pipes only after the game has started
    if (started && !gameOver) p.movePipe();

    // draw pipes
    p.show();

    // check if dog passes pipe for score
    if (!p.counted && dogX > p.x + p.w) {
      score++;
      p.counted = true;
    }

    // remove off-screen pipes
    if (p.x < -p.w) pipes.remove(i);
  }

  // add new pipes
  if (!gameOver && (pipes.size() == 0 || pipes.get(pipes.size()-1).x < width - 250)) {
    pipes.add(new Pipe(width));
  }

  // display score
  fill(255);
  textSize(30);
  text("Score: " + score, width - 100, 50);

  // lose screen
  if (gameOver) {
    fill(255, 0, 0);
    textSize(40);
    text("GAME OVER", width/2, height/2);
    textSize(20);
    text("Press R to Restart", width/2, height/2 + 50);
    noLoop(); // stop updating until restart
  }
}

class Pipe {
  float x; 
  float w = 120;      // width for both pipes
  float gap = 200;    // space between top and bottom pipe
  float speed = 3;    // how fast pipe moves
  float topHeight;  
  float bottomY;      
  float bottomHeight; 
  float groundY = 610;
  boolean counted = false;  // track if pipe has been passed for score

  Pipe(float startX) {
    x = startX;

    // safe random topHeight
    float minTop = 50;
    float maxTop = groundY - gap - 50;
    topHeight = random(minTop, maxTop);
    bottomY = topHeight + gap;
    bottomHeight = groundY - bottomY;
  }

  public void movePipe() {
    x -= speed;
  }

  public void show() {
    image(topBone, x, 0, w, topHeight);
    image(bottomBone, x, bottomY, w, bottomHeight);
  }
}

public void keyPressed() {
  if (key == ' ') {
    if (!started) started = true;
    if (!gameOver) velocity = jump;
  }
  if (gameOver && key == 'r') {
    // reset game
    dogPosY = 300;
    velocity = 0;
    pipes.clear();
    pipes.add(new Pipe(width));
    score = 0;
    gameOver = false;
    started = false;
    loop(); // resume drawing
  }
}


  public void settings() { size(600, 750); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "hackathonGame" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
